### ISSUE TITLE
Implement std::error::Error for ecies_ed25519::Error

### ISSUE THREAD

**Issue by ralfbiedert** [phayes/ecies-ed25519#4]
Hi,

It looks like `ecies_ed25519::Error` derives `#[derive(Debug, Fail)]`, but `Fail` does not make it implement `std::error::Error`.  As a result I can't use `thiserror::Error` with it:

```
error[E0599]: no method named `as_dyn_error` found for reference `&ecies_ed25519::Error` in the current scope
   --> tf_data_recorder\src\error.rs:63:13
    |
63  |     #[error("could not perform crypto operation")]
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&ecies_ed25519::Error`
    | 
   ::: C:\Users\rb\.cargo\registry\src\github.com-1ecc6299db9ec823\ecies-ed25519-0.4.0\src\lib.rs:150:1
    |
150 | pub enum Error {
    | --------------
    | |
    | doesn't satisfy `_: thiserror::aserror::AsDynError`
    | doesn't satisfy `ecies_ed25519::Error: std::error::Error`
    |
    = note: the method `as_dyn_error` exists but the following trait bounds were not satisfied:
            `ecies_ed25519::Error: std::error::Error`
            which is required by `ecies_ed25519::Error: thiserror::aserror::AsDynError`
            `&ecies_ed25519::Error: std::error::Error`
            which is required by `&ecies_ed25519::Error: thiserror::aserror::AsDynError`
```

And also:

```
error[E0277]: the trait bound `ecies_ed25519::Error: std::error::Error` is not satisfied
  --> tf_data_recorder\src\error.rs:69:7
   |
67 | fn f<T: std::error::Error>(t: &T) {
   |         ----------------- required by this bound in `error::f`
68 |     let e = ecies_ed25519::Error::DecryptionFailed;
69 |     f(&e);
   |       ^^ the trait `std::error::Error` is not implemented for `ecies_ed25519::Error`
```

**Comment by phayes** [comment]
This is now done!    New release to support this coming up.

**Comment by phayes** [comment]
This should now be working in the new 0.5 release.  Please re-open this ticket if any issues on this remain.
